name: Run sf.py Daily

on:
  schedule:
    - cron: "30 1 * * *"  
  workflow_dispatch:  

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run Python script
        run: python sf.py

      - name: Commit and push CSV file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sf.csv
          git commit -m "Update sf.csv" || exit 0
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
